#!/usr/bin/env bash
# extractors/lib/common.sh — shared helpers for deterministic extractors.
# Sourced by extract-auto-dependencies + extractors/<eco>.sh.
# NEVER call the network — extractors are offline-only.
#
# Note: callers should NOT rely on `set -u` since extractors manipulate
# many associative arrays that may stay empty (no repos found, no postinstall
# hooks, etc.) — bash treats `${#arr[@]}` on declared-but-empty assoc arrays
# as "unbound" under set -u, which we don't want.

# ───────────────────────────────────────────────────────────────
# find_manifests <search_root> <name_pattern> [<name_pattern>...]
#   Depth-bumped find. Starts at 3, retries at 5, 8, 10. Returns the
#   first non-empty list. Excludes node_modules, vendor, .git,
#   __pycache__, research-bundles.
# ───────────────────────────────────────────────────────────────
find_manifests() {
  local root="$1"
  shift
  local name_args=()
  local first=1
  for name in "$@"; do
    if [ $first -eq 1 ]; then
      name_args+=("-name" "$name")
      first=0
    else
      name_args+=("-o" "-name" "$name")
    fi
  done
  for depth in 3 5 8 10; do
    local found
    found=$(find "$root" -maxdepth "$depth" -type f \
      \( "${name_args[@]}" \) \
      -not -path '*/node_modules/*' \
      -not -path '*/vendor/*' \
      -not -path '*/.git/*' \
      -not -path '*/__pycache__/*' \
      -not -path '*/research-bundles/*' \
      2>/dev/null)
    if [ -n "$found" ]; then
      printf '%s\n' "$found"
      return 0
    fi
  done
  return 0
}

# ───────────────────────────────────────────────────────────────
# atomic_write <path> < stdin
#   Writes stdin to <path>.tmp then renames atomically. Avoids
#   partial reads if init-firewall.sh runs concurrently.
# ───────────────────────────────────────────────────────────────
atomic_write() {
  local path="$1"
  local tmp="${path}.tmp.$$"
  cat > "$tmp"
  mv -f "$tmp" "$path"
}

# ───────────────────────────────────────────────────────────────
# emit_header <ecosystem> <generator-cmd>
#   Standard header at the top of every generated domains.d/<eco>.txt.
# ───────────────────────────────────────────────────────────────
emit_header() {
  local ecosystem="$1"
  local generator="$2"
  cat <<EOF
# =============================================================================
# Auto-generated by ${generator}
# Ecosystem: ${ecosystem}
# Generated-at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT EDIT MANUALLY — re-run \`extract-auto-dependencies\` to regenerate.
# Manual additions go to firewall/domains.local.txt (gitignored, user overrides).
# =============================================================================

EOF
}

# ───────────────────────────────────────────────────────────────
# emit_format3_block <method-list> <host>
#   Prints the opening "[METHODS] host" line. Paths follow on indented
#   2-space lines (caller emits them).
# ───────────────────────────────────────────────────────────────
emit_format3_block() {
  local methods="$1"
  local host="$2"
  printf '[%s] %s\n' "$methods" "$host"
}

# ───────────────────────────────────────────────────────────────
# emit_format3_path <path> [<comment>]
# ───────────────────────────────────────────────────────────────
emit_format3_path() {
  local path="$1"
  local comment="${2:-}"
  if [ -n "$comment" ]; then
    printf '  %-40s # %s\n' "$path" "$comment"
  else
    printf '  %s\n' "$path"
  fi
}

# ───────────────────────────────────────────────────────────────
# lookup_doc_site <dep_name> <mapping_file>
#   Returns matching doc host from prefix-based lookup. Empty if no
#   match. Mapping format: <prefix><TAB><host>[<TAB><note>], one per line.
# ───────────────────────────────────────────────────────────────
lookup_doc_site() {
  local dep="$1"
  local mapping="$2"
  [ -f "$mapping" ] || return 0
  while IFS=$'\t' read -r prefix host note; do
    [ -z "${prefix:-}" ] && continue
    [[ "$prefix" =~ ^# ]] && continue
    if [[ "$dep" == "$prefix"* ]]; then
      printf '%s\n' "$host"
      return 0
    fi
  done < "$mapping"
  return 0
}
