#!/usr/bin/env bash
# @name scan-deps-banner
# @phase post-start
# @required false
# @description Scan-deps boot hook (F2) — banner if project manifests changed since the last `extract-auto-dependencies` run. Compares per-manifest mtime against the matching `domains.d/<eco>.txt` mtime (the deterministic allowlist file generated by extract-auto). If stale, suggests re-running the extractor.

set -eE

if [ -z "${SCAN_DEPS_HOOK_DISABLED:-}" ] && command -v python3 >/dev/null 2>&1; then
  python3 - <<'PY' || true
import os, subprocess
DOMAINS_D = '/workspace/.devcontainer/firewall/domains.d'
# F2: package.json → domains.d/npm.txt is the only auto-extracted ecosystem.
# composer.json / pyproject.toml / requirements.txt / Cargo.toml / go.mod still
# use /scan-deps — their staleness is handled by the skill, not this banner.
MANIFEST_NAME = 'package.json'
ECO_FILE = 'npm.txt'
def find_manifests(depths=(3, 5, 8, 10)):
    for d in depths:
        res = subprocess.run(
            ['find', '/workspace', '-maxdepth', str(d), '-type', 'f',
             '-name', MANIFEST_NAME,
             '-not', '-path', '*/node_modules/*',
             '-not', '-path', '*/vendor/*',
             '-not', '-path', '*/.git/*',
             '-not', '-path', '*/__pycache__/*',
             '-not', '-path', '*/research-bundles/*'],
            capture_output=True, text=True)
        ms = [p for p in res.stdout.splitlines() if p]
        if ms:
            return ms
    return []
manifests = find_manifests()
if not manifests:
    raise SystemExit
target = os.path.join(DOMAINS_D, ECO_FILE)
stale = False
if not os.path.exists(target):
    stale = True
else:
    try:
        target_mt = os.path.getmtime(target)
    except OSError:
        stale = True
    else:
        for m in manifests:
            try:
                if os.path.getmtime(m) > target_mt:
                    stale = True
                    break
            except OSError:
                continue
if stale:
    yellow = '\033[1;33m'
    reset = '\033[0m'
    lines = [
        '╔════════════════════════════════════════════════════════════════╗',
        '║  ⚠  Project manifests changed since last firewall extract      ║',
        '║                                                                ║',
        '║  Refresh the allowlist (deterministic, no AI) :                ║',
        '║     bash .devcontainer/skills/scan-deps/                       ║',
        '║          extract-auto-dependencies                             ║',
        '║                                                                ║',
        '║  Then reload the firewall :                                    ║',
        '║     sudo /usr/local/bin/init-firewall.sh                       ║',
        '║                                                                ║',
        '║  Or run /scan-deps in Claude for review + edge cases.          ║',
        '╚════════════════════════════════════════════════════════════════╝',
    ]
    print(yellow + '\n'.join(lines) + reset)
PY
fi
