#!/usr/bin/env bash
# master-review-suggest-fresh.sh — Claude Code Stop hook (D.1).
#
# Triggers a "open a fresh session" recommendation when the current review
# session crosses the saturation threshold:
#   - > 150 user prompts in the JSONL transcript
#   - AND a PR-*-review.md or PR-*-recap.md is currently modified in `git status`
#
# When triggered, emits a JSON Stop-hook output with `systemMessage` containing
# the kickoff prompt generated by master-review-gen-kickoff.sh — non-blocking,
# just a visible warning above the user's next turn.
#
# When NOT triggered, exits silently (no stdout, no stderr, exit 0).
#
# Stdin (Claude Code Stop hook contract):
#   {"session_id": "...", "transcript_path": "/path/to/jsonl",
#    "cwd": "...", "stop_hook_active": false}

set -uo pipefail

THRESHOLD="${REVIEW_SESSION_THRESHOLD:-150}"
GEN_KICKOFF="$(dirname "${BASH_SOURCE[0]}")/master-review-gen-kickoff.sh"

# Read hook input. If stdin empty or invalid JSON, fall back to env vars.
input=""
if [ ! -t 0 ]; then
	input=$(cat 2>/dev/null || true)
fi

# Extract transcript_path. Try jq first, then python, then leave empty.
transcript_path=""
if [[ -n "$input" ]]; then
	if command -v jq >/dev/null 2>&1; then
		transcript_path=$(echo "$input" | jq -r '.transcript_path // empty' 2>/dev/null || true)
	elif command -v python3 >/dev/null 2>&1; then
		transcript_path=$(echo "$input" | python3 -c 'import sys,json
try:
  d = json.load(sys.stdin)
  print(d.get("transcript_path",""))
except: pass' 2>/dev/null || true)
	fi
fi

# Test override: CLAUDE_SESSION_FILE wins over the JSON input. Also a fallback
# when the hook input is missing or unparseable.
if [[ -n "${CLAUDE_SESSION_FILE:-}" ]]; then
	transcript_path="$CLAUDE_SESSION_FILE"
fi

# Bail if no transcript to inspect.
if [[ -z "$transcript_path" || ! -f "$transcript_path" ]]; then
	exit 0
fi

# Count user prompts. Distinguish real user turns from sidechain / tool /
# system entries: type==user, userType==external, isSidechain not true.
user_prompts=$(python3 -c "
import json, sys
n = 0
try:
  with open(sys.argv[1]) as f:
    for line in f:
      try:
        d = json.loads(line)
      except Exception:
        continue
      if d.get('type') == 'user' and d.get('userType') == 'external' and not d.get('isSidechain'):
        n += 1
except Exception:
  pass
print(n)
" "$transcript_path" 2>/dev/null || echo 0)

if (( user_prompts <= THRESHOLD )); then
	exit 0
fi

# Detect a modified PR-*-review.md or PR-*-recap.md in the current repo.
review_file=""
if git rev-parse --git-dir >/dev/null 2>&1; then
	review_file=$(git status --porcelain 2>/dev/null \
		| awk '{ for (i=2;i<=NF;i++) print $i }' \
		| grep -E '(^|/)PR-[0-9]+-(review|recap)\.md$' \
		| head -1 || true)
fi

if [[ -z "$review_file" ]]; then
	exit 0
fi

# Pull the PR number out of the filename.
pr_number=$(echo "$review_file" | grep -oE 'PR-[0-9]+' | head -1 | grep -oE '[0-9]+')

# Build the kickoff body. If master-review-gen-kickoff.sh is missing or fails,
# fall back to a minimal warning so we still surface something.
kickoff=""
if [[ -n "$pr_number" && -x "$GEN_KICKOFF" ]]; then
	kickoff=$("$GEN_KICKOFF" "$pr_number" 2>/dev/null || true)
fi

if [[ -z "$kickoff" ]]; then
	kickoff="Saturated review session: ${user_prompts} user prompts, modified ${review_file}. Open a fresh session and resume from PR-${pr_number:-?}-recap.md."
fi

warning=$(printf '⚠️  Session at %s+ user turns on a review (modified: %s).\nOpen a fresh session and resume via the kickoff prompt below.\n\n%s' \
	"$user_prompts" "$review_file" "$kickoff")

# Emit a Stop-hook JSON output. `systemMessage` shows a non-blocking warning
# to the user above their next turn. We do NOT set `decision: block` — we
# don't want to fight the user's flow, just nudge.
python3 -c '
import json, sys
msg = sys.stdin.read()
print(json.dumps({"systemMessage": msg}))
' <<<"$warning"

exit 0
